future: true
syntax_highlighter: highlight.js
permalink_defaults: null
index_generator:
  path: ""
  per_page: 10
  order_by: -date
deploy:
  type: git
  repository: git@github.com:youqishi1/youqishi1.github.io.git
  branch: main
include: null
titlecase: false
date_format: YYYY-MM-DD
filename_case: 0
pagination_dir: page
tag_dir: tags
default_layout: post
time_format: HH:mm:ss
theme: anzhiyu
source_dir: source
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""
keywords:
  - LDLW
  - ldlw
author: 总结
new_post_name: :title.md
permalink: :year/:month/:day/:title/
category_dir: categories
i18n_dir: :lang
relative_link: false
pretty_urls:
  trailing_index: true
  trailing_html: true
external_link:
  enable: true
  field: site
  exclude: ""
url: https://1.8818866.xyz/
archive_dir: archives
per_page: 10
ignore: null
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
skip_render:
  - admin/**
public_dir: public
tag_map: null
subtitle: ""
title: LDLW
language: zh-cn
updated_option: mtime
meta_generator: true
timezone: 北京
exclude: null
render_drafts: false
category_map: null
code_dir: downloads/code
default_category: uncategorized
post_asset_folder: false
description: ""
